"""Tests for the route analysis tool.

These tests do not exercise any HTTP path — the tool reads local GPX files only.
The fixtures live in tests/fixtures/routes and are regenerated by running
`uv run python tests/fixtures/routes/_generate.py`.
"""

import json
from pathlib import Path

from intervals_icu_mcp.tools.routes import _characterise_segment, analyze_route_climbs

FIXTURES = Path(__file__).parent / "fixtures" / "routes"


def _load(result: str) -> dict:
    return json.loads(result)


class TestFlatRoute:
    """A near-flat route should yield zero climbs."""

    async def test_no_climbs_detected(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "flat_route.gpx"))
        r = _load(result)
        assert "data" in r
        assert r["data"]["climbs"] == []
        assert r["data"]["route_summary"]["total_distance_km"] > 9.0
        assert r["analysis"]["eligible_climb_count"] == 0


class TestSingleClimb:
    """2 km flat + 1.6 km @ 6% + 3 km descent should yield one Cat-3 climb."""

    async def test_one_climb_detected_with_expected_shape(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "single_climb.gpx"))
        r = _load(result)
        climbs = r["data"]["climbs"]
        assert len(climbs) == 1
        climb = climbs[0]
        # Climb should start near 2 km and have length close to 1.6 km.
        assert 1.8 <= climb["start_km"] <= 2.2
        assert 1500 <= climb["length_m"] <= 1700
        # Gradient should be close to 6%.
        assert 5.5 <= climb["avg_gradient_percent"] <= 6.5
        # Eligible for hard effort at cycling thresholds.
        assert climb["eligible_for_hard_effort"] is True
        # Should fall in the threshold/V02 zone for a ~7-10 min climb.
        assert climb["suggested_zone"] in ("Z4 threshold", "Z5 VO2max")

    async def test_recovery_segments_cover_flat_and_descent(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "single_climb.gpx"))
        r = _load(result)
        segments = r["data"]["recovery_segments"]
        # Expect one flat segment before the climb and one descent after.
        characters = [s["character"] for s in segments]
        assert "flat" in characters
        assert "descent" in characters
        # Each segment carries a hard_effort_recommended flag.
        for seg in segments:
            assert "hard_effort_recommended" in seg
        # Descents are never recommended for hard efforts.
        for seg in segments:
            if seg["character"] in ("descent", "shallow_descent"):
                assert seg["hard_effort_recommended"] is False


class TestMultiClimb:
    """Route with three climbs of different sizes."""

    async def test_three_climbs_detected(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "multi_climb.gpx"))
        r = _load(result)
        climbs = r["data"]["climbs"]
        assert len(climbs) == 3
        # First climb is the steep short kicker, then progressively longer climbs.
        assert climbs[0]["length_m"] < climbs[1]["length_m"] < climbs[2]["length_m"]
        # The short kicker should land in an anaerobic / V02 zone.
        assert climbs[0]["suggested_zone"] in ("Z5 VO2max", "Z6 anaerobic")
        # Eligible flags set for every detected climb (all are above 3% threshold).
        assert all(c["eligible_for_hard_effort"] for c in climbs)

    async def test_analysis_summarizes_climbing_time(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "multi_climb.gpx"))
        r = _load(result)
        assert r["analysis"]["eligible_climb_count"] == 3
        assert r["analysis"]["total_climbing_time_s"] > 0


class TestUndulatingClimb:
    """Recovery tolerance must merge a short flat spot inside a climb."""

    async def test_flat_spot_does_not_fragment_climb(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "undulating.gpx"))
        r = _load(result)
        climbs = r["data"]["climbs"]
        # The fixture has a single climbing section interrupted by 60 m of near-flat.
        # With cycling's 80 m recovery tolerance the two pieces must join into one climb.
        assert len(climbs) == 1
        # Combined length should exceed the longer of the two raw pieces (~700 m).
        assert climbs[0]["length_m"] > 1000


class TestRunningProfile:
    """Running profile detects shorter and steeper climbs than cycling."""

    async def test_running_picks_up_short_climbs(self):
        result = await analyze_route_climbs(
            gpx_path=str(FIXTURES / "running_route.gpx"),
            sport="running",
        )
        r = _load(result)
        climbs = r["data"]["climbs"]
        # Fixture has an 80 m and a 120 m climb — both above running min_length=50 m.
        assert len(climbs) == 2
        # Categories should be running-style buckets, not Tour-de-France categories.
        for c in climbs:
            assert c["category"] in ("short steep", "medium", "long sustained")

    async def test_cycling_profile_misses_short_running_climbs(self):
        # Same fixture under cycling thresholds — climbs are well below 200 m, so 0 detected.
        result = await analyze_route_climbs(
            gpx_path=str(FIXTURES / "running_route.gpx"),
            sport="cycling",
        )
        r = _load(result)
        assert r["data"]["climbs"] == []


class TestCustomThresholds:
    """Overrides should change what gets detected."""

    async def test_raising_min_gradient_filters_out_climbs(self):
        # The multi-climb route's third climb is exactly 4%; raising threshold to 5% drops it.
        result = await analyze_route_climbs(
            gpx_path=str(FIXTURES / "multi_climb.gpx"),
            min_gradient_percent=5.0,
        )
        r = _load(result)
        climbs = r["data"]["climbs"]
        # First two climbs (7.7% kicker, 5.5% middle) survive; the 4% climb is filtered.
        assert len(climbs) == 2
        assert all(c["avg_gradient_percent"] >= 5.0 for c in climbs)

    async def test_metadata_reports_thresholds_used(self):
        result = await analyze_route_climbs(
            gpx_path=str(FIXTURES / "single_climb.gpx"),
            min_gradient_percent=2.0,
            min_length_m=100.0,
        )
        r = _load(result)
        assert r["metadata"]["thresholds"]["min_gradient_percent"] == 2.0
        assert r["metadata"]["thresholds"]["min_length_m"] == 100.0


class TestErrorPaths:
    """Error paths must return structured error responses, not stack traces."""

    async def test_missing_file_returns_error(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "does_not_exist.gpx"))
        r = _load(result)
        assert "error" in r
        assert r["error"]["type"] == "route_parse_error"
        assert "not found" in r["error"]["message"].lower()
        assert r["error"]["suggestions"]

    async def test_gpx_without_elevation_returns_error(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "no_elevation.gpx"))
        r = _load(result)
        assert "error" in r
        assert r["error"]["type"] == "route_parse_error"
        assert "elevation" in r["error"]["message"].lower()


class TestGpxContent:
    """The gpx_content parameter lets Claude analyze user-attached files
    without needing them on the MCP server's filesystem."""

    async def test_content_produces_same_result_as_path(self):
        content = (FIXTURES / "single_climb.gpx").read_text()
        by_path = _load(await analyze_route_climbs(gpx_path=str(FIXTURES / "single_climb.gpx")))
        by_content = _load(await analyze_route_climbs(gpx_content=content))
        # Same number of climbs and same key shape values from both paths.
        assert len(by_path["data"]["climbs"]) == len(by_content["data"]["climbs"])
        assert by_path["data"]["climbs"][0]["length_m"] == by_content["data"]["climbs"][0]["length_m"]
        # Source label differs.
        assert by_path["metadata"]["source"] != "inline_content"
        assert by_content["metadata"]["source"] == "inline_content"

    async def test_invalid_xml_content_returns_error(self):
        result = await analyze_route_climbs(gpx_content="<not-gpx>nope</not-gpx>")
        r = _load(result)
        assert "error" in r
        assert r["error"]["type"] == "route_parse_error"

    async def test_providing_both_path_and_content_returns_error(self):
        content = (FIXTURES / "single_climb.gpx").read_text()
        result = await analyze_route_climbs(
            gpx_path=str(FIXTURES / "single_climb.gpx"),
            gpx_content=content,
        )
        r = _load(result)
        assert "error" in r
        assert r["error"]["type"] == "validation_error"

    async def test_providing_neither_returns_error(self):
        result = await analyze_route_climbs()
        r = _load(result)
        assert "error" in r
        assert r["error"]["type"] == "validation_error"


class TestSegmentCharacterisation:
    """The 5-bucket gradient classifier."""

    def test_descent(self):
        assert _characterise_segment(-3.0, climb_threshold_pct=3.0) == ("descent", False)
        assert _characterise_segment(-1.5, climb_threshold_pct=3.0) == ("descent", False)

    def test_shallow_descent(self):
        assert _characterise_segment(-1.0, climb_threshold_pct=3.0) == ("shallow_descent", False)
        assert _characterise_segment(-0.5, climb_threshold_pct=3.0) == ("shallow_descent", False)

    def test_flat(self):
        assert _characterise_segment(0.0, climb_threshold_pct=3.0) == ("flat", False)
        assert _characterise_segment(0.4, climb_threshold_pct=3.0) == ("flat", False)

    def test_shallow_rise_is_hard_effort_eligible(self):
        # Between the "flat" upper bound and the climb threshold.
        assert _characterise_segment(0.5, climb_threshold_pct=3.0) == ("shallow_rise", True)
        assert _characterise_segment(2.5, climb_threshold_pct=3.0) == ("shallow_rise", True)

    def test_running_profile_uses_its_own_threshold(self):
        # At running's 4% threshold, a 3.5% segment is shallow_rise, not a missed climb.
        assert _characterise_segment(3.5, climb_threshold_pct=4.0) == ("shallow_rise", True)


class TestWarmupRecommendation:
    """Analysis must always include a warmup recommendation for safety."""

    async def test_warmup_present_when_climbs_exist(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "single_climb.gpx"))
        r = _load(result)
        warmup = r["analysis"]["warmup_recommendation"]
        assert warmup["min_duration_minutes"] == 15  # cycling default
        assert warmup["first_climb_km"] is not None
        assert "warm-up" in warmup["note"].lower() or "z1" in warmup["note"].lower()

    async def test_warmup_present_when_no_climbs(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "flat_route.gpx"))
        r = _load(result)
        warmup = r["analysis"]["warmup_recommendation"]
        assert warmup["min_duration_minutes"] == 15
        assert warmup["first_climb_km"] is None

    async def test_running_warmup_default_shorter_than_cycling(self):
        result = await analyze_route_climbs(
            gpx_path=str(FIXTURES / "running_route.gpx"), sport="running"
        )
        r = _load(result)
        assert r["analysis"]["warmup_recommendation"]["min_duration_minutes"] == 10


class TestCompositionTips:
    """Analysis must include workout-composition tips Claude can follow."""

    async def test_tips_present_and_nonempty(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "single_climb.gpx"))
        r = _load(result)
        tips = r["analysis"]["composition_tips"]
        assert isinstance(tips, list)
        assert len(tips) >= 3
        joined = " ".join(tips).lower()
        # Tips must mention the 10s prep step and the no-hard-on-descent rule.
        assert "10s" in joined or "prep" in joined
        assert "descent" in joined


class TestProfileShape:
    """The elevation profile should always be present and roughly downsampled."""

    async def test_profile_downsampled_to_expected_size(self):
        result = await analyze_route_climbs(gpx_path=str(FIXTURES / "multi_climb.gpx"))
        r = _load(result)
        profile = r["data"]["elevation_profile"]
        # Source has 611 points; downsampling should bring it to ~80.
        assert 70 <= len(profile) <= 90
        # Profile keys are stable.
        assert {"km", "ele_m"} == set(profile[0].keys())
